#!/usr/bin/env python3
"""
Calibrate a Gear 360 and write a viewer-compatible calibration.toml.

Modes
-----
Run calibration on a real image or video (primary use):
  python create_calibration.py --image frame.jpg       -o calibration.toml
  python create_calibration.py --video clip.avi        -o calibration.toml
  python create_calibration.py --video clip.avi        -o calibration.toml --solver adjoint

Per-solver tuning lives in:
  solvers/configs/adjoint_tuning.toml    --solver adjoint
  solvers/configs/features_tuning.toml   --solver features
  solvers/configs/plumbline_tuning.toml  --solver plumbline
Override any with --config <path>.

Video frame picking is controlled by the [video_sampling] section of the
solver-appropriate tuning file (frame_stride, start_frame), with --frames /
--frame-stride on the command line as overrides.

Convert an existing optimizer JSON to TOML:
  python create_calibration.py --from-json result.json -o calibration.toml

Write a baseline TOML with Gear 360 defaults (no image needed):
  python create_calibration.py --preset gear360        -o calibration.toml

The output TOML is readable by both the C++ viewer (cpp/calibration.toml)
and the Python viewer (--calibration / viewer.toml calibration key).
"""

import argparse
import json
import math
import os
import sys
from pathlib import Path


# ---------------------------------------------------------------------------
# TOML writer
# ---------------------------------------------------------------------------

def _fov_to_scale(v: float) -> float:
    """Normalise FOV to a scale factor (1.0 = 180 deg).

    calibration_config.py stores FOV in degrees (e.g. 195.0).
    create_calibration's own default dict stores it as a scale factor (e.g. 1.083).
    Anything > 10 is treated as degrees.
    """
    return v / 180.0 if v > 10.0 else v


def write_toml(params: dict, path: str, method: str = "create_calibration") -> None:
    """Write a calibration.toml compatible with cpp/calibration.toml.

    params is the flat dict produced by CameraCalibration.to_dict() or
    create_calibration.py's own _default_params().

    Field mapping:
      lens1CenterX/Y          -> [lens1] center_x / center_y
      lens1K1/K2/K3           -> [lens1] p1 / p2 / p3  (p4 always 0)
      lens1FOV / lens2FOV     -> averaged into [metadata] fov_deg (degrees only)
      lens1RotationYaw/...    -> [lens1] rotation_* (degrees)
    """
    lines = [
        "# Samsung Gear 360 Camera Calibration Parameters",
        f"# Generated by create_calibration.py  (method: {method})",
        "# Compatible with cpp/calibration.toml and python/viewer.toml --calibration",
        "",
    ]

    for lens, px in (("lens1", "lens1"), ("lens2", "lens2")):
        lines += [
            f"[{lens}]",
            "# Lens center (normalized 0-1)",
            f"center_x = {params.get(f'{px}CenterX', 0.5):.6f}",
            f"center_y = {params.get(f'{px}CenterY', 0.5):.6f}",
            "",
            "# Polynomial distortion coefficients: r = f*t*(1 + p1*t + p2*t^2 + p3*t^3 + p4*t^4)",
            f"p1 = {params.get(f'{px}K1', 0.0):.6f}",
            f"p2 = {params.get(f'{px}K2', 0.0):.6f}",
            f"p3 = {params.get(f'{px}K3', 0.0):.6f}",
            f"p4 = 0.0",
            "",
            "# Per-lens rotation (degrees)",
            f"rotation_yaw   = {math.degrees(params.get(f'{px}RotationYaw',   0.0)):.4f}",
            f"rotation_pitch = {math.degrees(params.get(f'{px}RotationPitch', 0.0)):.4f}",
            f"rotation_roll  = {math.degrees(params.get(f'{px}RotationRoll',  0.0)):.4f}",
            "",
            "# Per-lens alignment offset (normalized 0-1)",
            f"offset_x = {params.get(f'{px}OffsetX', 0.0):.6f}",
            f"offset_y = {params.get(f'{px}OffsetY', 0.0):.6f}",
            "",
        ]

    deg1 = _fov_to_scale(params.get("lens1FOV", 195.0 / 180.0)) * 180.0
    deg2 = _fov_to_scale(params.get("lens2FOV", 195.0 / 180.0)) * 180.0
    fov_deg_out = (deg1 + deg2) / 2.0
    lines += [
        "[metadata]",
        "# Fisheye FOV in degrees (viewer uses scale = fov_deg / 180 for both lenses)",
        f"fov_deg = {fov_deg_out:.1f}",
        f'calibration_method = "{method}"',
        "",
    ]

    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def _default_params(fov_deg: float = 195.0) -> dict:
    """Flat params dict for a baseline calibration (all corrections zero)."""
    scale = fov_deg / 180.0
    return {
        "lens1CenterX": 0.5,  "lens1CenterY": 0.5,  "lens1FOV": scale,
        "lens1K1": 0.0,       "lens1K2": 0.0,       "lens1K3": 0.0,
        "lens1RotationYaw": 0.0, "lens1RotationPitch": 0.0, "lens1RotationRoll": 0.0,
        "lens1OffsetX": 0.0,  "lens1OffsetY": 0.0,
        "lens2CenterX": 0.5,  "lens2CenterY": 0.5,  "lens2FOV": scale,
        "lens2K1": 0.0,       "lens2K2": 0.0,       "lens2K3": 0.0,
        "lens2RotationYaw": 0.0, "lens2RotationPitch": 0.0, "lens2RotationRoll": 0.0,
        "lens2OffsetX": 0.0,  "lens2OffsetY": 0.0,
    }


# ---------------------------------------------------------------------------
# Video sampling (from the solver's tuning toml [video_sampling])
# ---------------------------------------------------------------------------

_DEFAULT_VIDEO_SAMPLING = {"frame_stride": 1, "start_frame": 0}


def _read_video_sampling(toml_path: str | Path | None) -> dict:
    """Load [video_sampling] from a tuning TOML, or return defaults."""
    out = dict(_DEFAULT_VIDEO_SAMPLING)
    if not toml_path:
        return out
    p = Path(toml_path)
    if not p.exists():
        return out
    try:
        try:
            import tomllib
            with open(p, "rb") as f:
                data = tomllib.load(f)
        except ImportError:
            import toml as tomllib  # type: ignore
            with open(p, "r", encoding="utf-8") as f:
                data = tomllib.load(f)
    except Exception:
        return out
    sec = data.get("video_sampling") or {}
    if not isinstance(sec, dict):
        return out
    if "frame_stride" in sec:
        out["frame_stride"] = max(1, int(sec["frame_stride"]))
    if "start_frame" in sec:
        out["start_frame"] = max(0, int(sec["start_frame"]))
    return out


# ---------------------------------------------------------------------------
# Frame loading
# ---------------------------------------------------------------------------

def _load_frames(
    image: str | None,
    video: str | None,
    n_frames: int,
    scale: float,
    *,
    frame_stride: int = 1,
    start_frame: int = 0,
):
    """Return list of (left_img, right_img) numpy arrays and the first raw frame.

    For ``--video``:
      * ``frame_stride <= 1``: pick ``n_frames`` indices spread evenly from the
        first to the last frame (legacy behaviour).
      * ``frame_stride >= 2``: take ``start_frame``, ``start_frame + stride``,
        ``start_frame + 2*stride``, ... until ``n_frames`` samples are collected
        or the video ends.
    """
    try:
        import cv2
        import numpy as np
    except ImportError:
        sys.exit("opencv-python is required: pip install opencv-python")

    frames = []
    source_frame = None

    if image:
        print(f"Loading image: {image}")
        img = cv2.imread(image)
        if img is None:
            sys.exit(f"Error: cannot load {image}")
        h, w = img.shape[:2]
        left, right = img[:, :w // 2], img[:, w // 2:]
        source_frame = (left, right)
        frames = [(left, right)]
    else:
        print(f"Loading video: {video}")
        cap = cv2.VideoCapture(video)
        if not cap.isOpened():
            sys.exit(f"Error: cannot open {video}")
        total = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
        if total <= 0:
            cap.release()
            sys.exit("Error: video reports zero frames")

        stride = max(1, int(frame_stride))
        if stride <= 1:
            indices = [int(i) for i in
                       __import__("numpy").linspace(0, total - 1, min(n_frames, total))]
        else:
            start = max(0, min(int(start_frame), total - 1))
            indices = []
            idx = start
            while len(indices) < n_frames and idx < total:
                indices.append(idx)
                idx += stride
            if not indices:
                cap.release()
                sys.exit(
                    f"Error: no frames selected (start_frame={start_frame}, "
                    f"total_frames={total}, frame_stride={stride})"
                )

        print(f"  Video sampling: stride={stride}, start={start_frame}, "
              f"max_samples={n_frames}, picked {len(indices)} frame index(es)")
        if len(indices) <= 12:
            print(f"    indices: {indices}")
        else:
            print(f"    indices: {indices[:6]} ... {indices[-3:]}")

        for idx in indices:
            cap.set(cv2.CAP_PROP_POS_FRAMES, idx)
            ret, frame = cap.read()
            if ret:
                h, w = frame.shape[:2]
                l, r = frame[:, :w // 2], frame[:, w // 2:]
                frames.append((l, r))
                if source_frame is None:
                    source_frame = (l, r)
        cap.release()
        print(f"  Loaded {len(frames)} frames from {total} total")

    if not frames:
        sys.exit("No frames loaded.")

    if scale < 1.0:
        import cv2
        scaled = []
        for l, r in frames:
            h, w = l.shape[:2]
            nh, nw = int(h * scale), int(w * scale)
            scaled.append((
                cv2.resize(l, (nw, nh), interpolation=cv2.INTER_AREA),
                cv2.resize(r, (nw, nh), interpolation=cv2.INTER_AREA),
            ))
        h0, w0 = frames[0][0].shape[:2]
        print(f"  Downsampled to {int(w0 * scale)}x{int(h0 * scale)}")
        frames = scaled

    return frames, source_frame


# ---------------------------------------------------------------------------
# Solver dispatch
# ---------------------------------------------------------------------------

# Tuning TOMLs live under solvers/configs/ (next to the solver code, where
# OptimizationConfig also looks for them as DEFAULT_CONFIG_PATH).
_SOLVER_CONFIGS_DIR       = Path(__file__).parent.parent / "solvers" / "configs"
_DEFAULT_ADJOINT_TUNING   = _SOLVER_CONFIGS_DIR / "adjoint_tuning.toml"
_DEFAULT_FEATURES_TUNING  = _SOLVER_CONFIGS_DIR / "features_tuning.toml"
_DEFAULT_PLUMBLINE_TUNING = _SOLVER_CONFIGS_DIR / "plumbline_tuning.toml"


def _resolve_config_path(solver: str, explicit: str | None) -> Path | None:
    """Pick the tuning TOML for ``solver``.

    Precedence: explicit ``--config`` > the solver's canonical file in
    ``calib/`` > None (caller falls back to compiled defaults).
    """
    if explicit:
        return Path(explicit)
    if solver == "features" and _DEFAULT_FEATURES_TUNING.exists():
        return _DEFAULT_FEATURES_TUNING
    if solver == "adjoint" and _DEFAULT_ADJOINT_TUNING.exists():
        return _DEFAULT_ADJOINT_TUNING
    if solver == "plumbline" and _DEFAULT_PLUMBLINE_TUNING.exists():
        return _DEFAULT_PLUMBLINE_TUNING
    return None


def _run_solver(frames, fov: float, solver: str, restarts: int, fix_lens1: bool,
                config_toml: str | None,
                seam_overlap_deg: float | None = None,
                seam_overlap_center_deg: float | None = None,
                preview: bool = False,
                detector: str | None = None,
                feat_ratio: float | None = None,
                feat_ransac_deg: float | None = None,
                feat_no_rotation: bool = False):
    """Call the requested solver and return a CameraCalibration object."""
    here = Path(__file__).resolve().parent
    root = here.parent.parent  # python/

    # Make sure imports resolve whether we're run as a module or directly
    if str(root) not in sys.path:
        sys.path.insert(0, str(root))

    if solver == "adjoint":
        from camera_calibration.solvers.calibrate_adjoint import (
            calibrate_with_config, OptimizationConfig,
        )
        cfg_path = _resolve_config_path("adjoint", config_toml)
        if config_toml:
            print(f"Adjoint tuning : {cfg_path}")
            cfg = OptimizationConfig(str(cfg_path), require_config=True)
        elif cfg_path is not None:
            print(f"Adjoint tuning : {cfg_path}")
            cfg = OptimizationConfig(str(cfg_path))
        else:
            print("Adjoint tuning : <built-in defaults>")
            cfg = OptimizationConfig(None)
        if seam_overlap_deg is not None:
            cfg.preprocessing['seam_overlap_deg'] = float(seam_overlap_deg)
        if seam_overlap_center_deg is not None:
            cfg.preprocessing['seam_overlap_center_deg'] = float(seam_overlap_center_deg)
        return calibrate_with_config(frames, fov, cfg, preview=preview)

    if solver == "features":
        from camera_calibration.solvers.calibrate_adjoint import OptimizationConfig
        from camera_calibration.solvers.calibrate_features import calibrate_features
        cfg_path = _resolve_config_path("features", config_toml)
        cfg = None
        if config_toml:
            print(f"Features tuning: {cfg_path}")
            cfg = OptimizationConfig(str(cfg_path), require_config=True)
        elif cfg_path is not None:
            print(f"Features tuning: {cfg_path}")
            cfg = OptimizationConfig(str(cfg_path))
        else:
            print("Features tuning: <built-in defaults>")
        return calibrate_features(
            frames, fov,
            detector_name=detector,
            ratio=feat_ratio,
            ransac_angle_deg=feat_ransac_deg,
            allow_rotation=not feat_no_rotation,
            config=cfg,
            preview=preview,
        )

    if solver == "plumbline":
        from camera_calibration.solvers.calibrate_adjoint import OptimizationConfig
        from camera_calibration.solvers.calibrate_plumbline import calibrate_plumbline
        cfg_path = _resolve_config_path("plumbline", config_toml)
        cfg = None
        if config_toml:
            print(f"Plumb-line tuning: {cfg_path}")
            cfg = OptimizationConfig(str(cfg_path), require_config=True)
        elif cfg_path is not None:
            print(f"Plumb-line tuning: {cfg_path}")
            cfg = OptimizationConfig(str(cfg_path))
        else:
            print("Plumb-line tuning: <built-in defaults>")
        return calibrate_plumbline(frames, fov, config=cfg, preview=preview)

    if preview:
        print("Note: --preview is currently only supported by the adjoint, "
              "features, and plumbline solvers; stepwise will run without a live window.")
    # default: stepwise
    from camera_calibration.solvers.calibrate_stepwise import calibrate_stepwise
    return calibrate_stepwise(frames, fov, n_restarts=restarts, fix_lens1=fix_lens1)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Calibrate a Gear 360 and write calibration.toml.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )

    # Input source
    src = parser.add_mutually_exclusive_group()
    src.add_argument("--image", "-i", metavar="FILE",
                     help="Single dual-fisheye image (left|right side-by-side)")
    src.add_argument("--video", metavar="FILE",
                     help="Video file — evenly-spaced frames are sampled")
    src.add_argument("--from-json", metavar="JSON_FILE",
                     help="Convert an existing optimizer JSON result to TOML; "
                          "skips calibration")
    src.add_argument("--preset", choices=["gear360", "theta"],
                     help="Write a baseline TOML with default values; no image needed")

    # Output
    parser.add_argument("-o", "--output", required=True,
                        help="Output file path (.toml recommended)")
    parser.add_argument("--save-json", metavar="FILE",
                        help="Also save the raw calibration JSON")

    # Solver options
    parser.add_argument("--solver",
                        choices=["stepwise", "adjoint", "features", "plumbline"],
                        default="stepwise",
                        help="Calibration solver to use (default: stepwise).  "
                             "'features' = SIFT/ORB seam matching + LM (good "
                             "when seam has texture).  'plumbline' = detect "
                             "straight world lines and fit lens model so "
                             "their rays are coplanar (good for distortion / "
                             "FOV when scene has architecture; rotations are "
                             "unobservable).  'adjoint' = photometric.")
    parser.add_argument("--fov", type=float, default=180.0,
                        help="Equirectangular base FOV per lens half, in degrees "
                             "(default: 180 -- a hemisphere). The PHYSICAL lens FOV "
                             "(e.g. ~195 for Gear 360) lives in the solver's tuning "
                             "TOML as [lens1.fov].nominal -- not here. lens.fov MUST "
                             "exceed this base, otherwise there is no overlap to "
                             "optimize.")
    parser.add_argument("--frames", type=int, default=5,
                        help="Max number of video frames to use (default: 5).  With "
                             "frame_stride>1 in [video_sampling], this caps how many "
                             "stride-spaced frames are kept.")
    parser.add_argument("--frame-stride", type=int, default=None, metavar="N",
                        help="Override [video_sampling].frame_stride from the "
                             "solver's tuning TOML "
                             "(1 = evenly spread across clip; 15 = every 15th frame)")
    parser.add_argument("--scale", type=float, default=None,
                        help="Downsample scale for faster optimization "
                             "(default: 0.25 for stepwise/adjoint, 1.0 for "
                             "features -- the features solver runs detection "
                             "only once and benefits from full resolution).")
    parser.add_argument("--restarts", type=int, default=3,
                        help="Random restarts for stepwise solver (default: 3)")
    parser.add_argument("--fix-lens1", action="store_true",
                        help="Fix lens 1 rotation at 0 (stepwise solver)")
    parser.add_argument("--config", metavar="TOML",
                        help="Override the auto-resolved tuning TOML.  By "
                             "default the solver-appropriate file under "
                             "solvers/configs/ is used (adjoint_tuning.toml, "
                             "features_tuning.toml, plumbline_tuning.toml).")
    parser.add_argument("--seam-overlap-deg", type=float, default=None,
                        help="Adjoint solver only.  Total seam-strip width in "
                             "DEGREES OF FOV.  0 = use the full geometric "
                             "overlap (legacy).  Pair with --seam-overlap-center-deg "
                             "to anchor the strip.  Overrides "
                             "[preprocessing].seam_overlap_deg in adjoint_tuning.toml.")
    parser.add_argument("--seam-overlap-center-deg", type=float, default=None,
                        help="Adjoint solver only.  FIXED centre of the seam-strip "
                             "in degrees of FOV (does NOT track the dynamic "
                             "lens.fov, so the optimiser can't game it).  "
                             "0 = base_fov (180 deg).  E.g. with --seam-overlap-deg=2 "
                             "and --seam-overlap-center-deg=185 the strip is FOV "
                             "[184, 186].  Overrides [preprocessing]."
                             "seam_overlap_center_deg in adjoint_tuning.toml.")
    parser.add_argument("--preview", action="store_true",
                        help="Open a live OpenCV window showing the stitched "
                             "first frame, refreshed every generation.  For "
                             "videos this uses the first sampled frame; for "
                             "images it uses the image itself.  Adjoint and "
                             "features solvers only.")

    # Feature solver options.  Defaults are intentionally None: when omitted
    # the value comes from features_tuning.toml's [features] section.
    parser.add_argument("--detector", choices=["sift", "orb", "akaze"],
                        default=None,
                        help="Features solver only.  Local feature detector "
                             "(overrides [features].detector in "
                             "features_tuning.toml; built-in default: sift).")
    parser.add_argument("--ratio", type=float, default=None,
                        help="Features solver only.  Lowe ratio test threshold "
                             "(overrides [features].ratio; built-in: 0.85).  "
                             "Raise toward 0.92 if too few matches survive.")
    parser.add_argument("--ransac-deg", type=float, default=None,
                        help="Features solver only.  Inlier angular tolerance "
                             "in degrees (overrides [features].ransac_deg; "
                             "built-in: 5.0).  Raise to 10-20 if the nominal "
                             "calibration is far from the truth.")
    parser.add_argument("--no-rotation", action="store_true",
                        help="Features solver only.  Pin lens rotations at "
                             "their initial values (typically zero); only "
                             "solve for centre / FOV / distortion.")

    args = parser.parse_args()

    if not args.image and not args.video and not args.from_json and not args.preset:
        parser.error("provide --image, --video, --from-json, or --preset")

    # Solver-aware default for --scale.  Features and plumbline both run
    # detectors that benefit from full resolution; adjoint/stepwise downsample
    # for speed.
    if args.scale is None:
        args.scale = 1.0 if args.solver in ("features", "plumbline") else 0.25

    # ----------------------------------------------------------------
    # Mode 1: --from-json  (convert existing result)
    # ----------------------------------------------------------------
    if args.from_json:
        with open(args.from_json) as f:
            cal = json.load(f)
        params = cal.get("parameters", cal)
        method = f"converted_from:{os.path.basename(args.from_json)}"
        write_toml(params, args.output, method)
        print(f"Converted {args.from_json} -> {args.output}")
        _print_usage(args.output)
        return

    # ----------------------------------------------------------------
    # Mode 2: --preset  (baseline TOML, no image)
    # ----------------------------------------------------------------
    if args.preset:
        fov = {"gear360": 195.0, "theta": 180.0}[args.preset]
        params = _default_params(fov)
        write_toml(params, args.output, f"preset_{args.preset}")
        print(f"Created baseline TOML ({args.preset}, {fov} deg FOV): {args.output}")
        _print_usage(args.output)
        return

    # ----------------------------------------------------------------
    # Mode 3: --image / --video  (run calibration)
    # ----------------------------------------------------------------
    # Pull video sampling from whichever tuning file the chosen solver uses.
    sampling_path = _resolve_config_path(args.solver, args.config)
    tuning_for_sampling = str(sampling_path) if sampling_path is not None else None
    vs = _read_video_sampling(tuning_for_sampling)
    stride = args.frame_stride if args.frame_stride is not None else vs["frame_stride"]
    start = vs["start_frame"]
    if args.video:
        print(f"Video sampling from {tuning_for_sampling or 'defaults'}: "
              f"frame_stride={stride}, start_frame={start}")

    frames, source_frame = _load_frames(
        args.image,
        args.video,
        args.frames,
        args.scale,
        frame_stride=stride,
        start_frame=start,
    )

    print(f"\nRunning {args.solver} solver ({len(frames)} frame(s), base projection FOV={args.fov} deg) ...")
    calib = _run_solver(frames, args.fov, args.solver, args.restarts,
                        args.fix_lens1, args.config,
                        seam_overlap_deg=args.seam_overlap_deg,
                        seam_overlap_center_deg=args.seam_overlap_center_deg,
                        preview=args.preview,
                        detector=args.detector,
                        feat_ratio=args.ratio,
                        feat_ransac_deg=args.ransac_deg,
                        feat_no_rotation=args.no_rotation)

    params = calib.to_dict()

    if args.save_json:
        with open(args.save_json, "w") as f:
            json.dump({"parameters": params}, f, indent=2)
        print(f"JSON saved: {args.save_json}")

    write_toml(params, args.output, method=f"{args.solver}_optimizer")
    print(f"TOML saved: {args.output}")

    l1, l2 = calib.lens1, calib.lens2
    print(f"  Lens 1: center=({l1.center_x:.4f}, {l1.center_y:.4f})  "
          f"fov={l1.fov:.2f} deg  k1={l1.k1:.4f}")
    print(f"  Lens 2: center=({l2.center_x:.4f}, {l2.center_y:.4f})  "
          f"fov={l2.fov:.2f} deg  k1={l2.k1:.4f}")

    _print_usage(args.output)


def _print_usage(output_path: str) -> None:
    print()
    print("Use with the Python viewer:")
    print(f"  gear360_viewer.py --calibration {output_path}")
    print(f"  or set in python/viewer.toml:  calibration = \"{output_path}\"")
    print("Copy to use with the C++ viewer:")
    print(f"  cpp/calibration.toml")


if __name__ == "__main__":
    main()
